[package]
name = "midi2idim"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bus = "2.3.0"

[build-dependencies]
cbindgen = "0.24.3"
cargo-generate = "0.17.4"


