typedef short int16_t;
enum js_var_type {JS_VAR_NULL, JS_VAR_UNDEFINED, JS_VAR_NAN, JS_VAR_BOOL, JS_VAR_INT16, JS_VAR_STRING, JS_VAR_ARRAY, JS_VAR_DICT};
struct js_var {
    enum js_var_type type;
    int16_t number;
    void *data;
};
struct js_var js_var_from(enum js_var_type type) {
    struct js_var v;
    v.type = type;
    v.data = NULL;
    return v;
}
int main(void) {
    /* Unsupported node: type cmidi2_ci_protocol_tag = { protocol_type: number// cmidi2_ci_protocol_bytes version: number // cmidi2_ci_protocol_values extensions: number // cmidi2_ci_protocol_extensions (flags) reserved1: number reserved2: number }; */;
    /* Unsupported node: enum midi2_status_code { STATUS_NOTE_OFF = 0x80, STATUS_NOTE_ON = 0x90, STATUS_PAF = 0xA0, STATUS_CC = 0xB0, STATUS_PROGRAM = 0xC0, STATUS_CAF = 0xD0, STATUS_PITCH_BEND = 0xE0, STATUS_PER_NOTE_RCC = 0x00, STATUS_PER_NOTE_ACC = 0x10, STATUS_RPN = 0x20, STATUS_NRPN = 0x30, STATUS_RELATIVE_RPN = 0x40, STATUS_RELATIVE_NRPN = 0x50, STATUS_PER_NOTE_PITCH_BEND = 0x60, STATUS_PER_NOTE_MANAGEMENT = 0xF0, } */;
    ;
    /* Unsupported node: enum cmidi2_message_type { // MIDI 2.0 UMP Section 3. CMIDI2_MESSAGE_TYPE_UTILITY = 0, CMIDI2_MESSAGE_TYPE_SYSTEM = 1, CMIDI2_MESSAGE_TYPE_MIDI_1_CHANNEL = 2, CMIDI2_MESSAGE_TYPE_SYSEX7 = 3, CMIDI2_MESSAGE_TYPE_MIDI_2_CHANNEL = 4, CMIDI2_MESSAGE_TYPE_SYSEX8_MDS = 5, } */;
    ;
    /* Unsupported node: enum cmidi2_ci_protocol_bytes { CMIDI2_PROTOCOL_BYTES_TYPE = 1, CMIDI2_PROTOCOL_BYTES_VERSION = 2, CMIDI2_PROTOCOL_BYTES_EXTENSIONS = 3, } */;
    ;
    /* Unsupported node: enum cmidi2_ci_protocol_values { CMIDI2_PROTOCOL_TYPE_MIDI1 = 1, CMIDI2_PROTOCOL_TYPE_MIDI2 = 2, CMIDI2_PROTOCOL_VERSION_MIDI1 = 0, CMIDI2_PROTOCOL_VERSION_MIDI2_V1 = 0, } */;
    ;
    /* Unsupported node: enum cmidi2_ci_protocol_extensions { CMIDI2_PROTOCOL_EXTENSIONS_JITTER = 1, CMIDI2_PROTOCOL_EXTENSIONS_LARGER = 2, // only for MIDI 1.0 compat UMP } */;
    ;
    /* Unsupported node: enum cmidi2_cc { CMIDI2_CC_BANK_SELECT = 0x00, CMIDI2_CC_MODULATION = 0x01, CMIDI2_CC_BREATH = 0x02, CMIDI2_CC_FOOT = 0x04, CMIDI2_CC_PORTAMENTO_TIME = 0x05, CMIDI2_CC_DTE_MSB = 0x06, CMIDI2_CC_VOLUME = 0x07, CMIDI2_CC_BALANCE = 0x08, CMIDI2_CC_PAN = 0x0A, CMIDI2_CC_EXPRESSION = 0x0B, CMIDI2_CC_EFFECT_CONTROL_1 = 0x0C, CMIDI2_CC_EFFECT_CONTROL_2 = 0x0D, CMIDI2_CC_GENERAL_1 = 0x10, CMIDI2_CC_GENERAL_2 = 0x11, CMIDI2_CC_GENERAL_3 = 0x12, CMIDI2_CC_GENERAL_4 = 0x13, CMIDI2_CC_BANK_SELECT_LSB = 0x20, CMIDI2_CC_MODULATION_LSB = 0x21, CMIDI2_CC_BREATH_LSB = 0x22, CMIDI2_CC_FOOT_LSB = 0x24, CMIDI2_CC_PORTAMENTO_TIME_LSB = 0x25, CMIDI2_CC_DTE_LSB = 0x26, CMIDI2_CC_VOLUME_LSB = 0x27, CMIDI2_CC_BALANCE_LSB = 0x28, CMIDI2_CC_PAN_LSB = 0x2A, CMIDI2_CC_EXPRESSION_LSB = 0x2B, CMIDI2_CC_EFFECT1_LSB = 0x2C, CMIDI2_CC_EFFECT2_LSB = 0x2D, CMIDI2_CC_GENERAL_1_LSB = 0x30, CMIDI2_CC_GENERAL_2_LSB = 0x31, CMIDI2_CC_GENERAL_3_LSB = 0x32, CMIDI2_CC_GENERAL_4_LSB = 0x33, CMIDI2_CC_HOLD = 0x40, CMIDI2_CC_PORTAMENTO_SWITCH = 0x41, CMIDI2_CC_SOSTENUTO = 0x42, CMIDI2_CC_SOFT_PEDAL = 0x43, CMIDI2_CC_LEGATO = 0x44, CMIDI2_CC_HOLD_2 = 0x45, CMIDI2_CC_SOUND_CONTROLLER_1 = 0x46, CMIDI2_CC_SOUND_CONTROLLER_2 = 0x47, CMIDI2_CC_SOUND_CONTROLLER_3 = 0x48, CMIDI2_CC_SOUND_CONTROLLER_4 = 0x49, CMIDI2_CC_SOUND_CONTROLLER_5 = 0x4A, CMIDI2_CC_SOUND_CONTROLLER_6 = 0x4B, CMIDI2_CC_SOUND_CONTROLLER_7 = 0x4C, CMIDI2_CC_SOUND_CONTROLLER_8 = 0x4D, CMIDI2_CC_SOUND_CONTROLLER_9 = 0x4E, CMIDI2_CC_SOUND_CONTROLLER_10 = 0x4F, CMIDI2_CC_GENERAL_5 = 0x50, CMIDI2_CC_GENERAL_6 = 0x51, CMIDI2_CC_GENERAL_7 = 0x52, CMIDI2_CC_GENERAL_8 = 0x53, CMIDI2_CC_PORTAMENTO_CONTROL = 0x54, CMIDI2_CC_RSD = 0x5B, CMIDI2_CC_EFFECT_1 = 0x5B, CMIDI2_CC_TREMOLO = 0x5C, CMIDI2_CC_EFFECT_2 = 0x5C, CMIDI2_CC_CSD = 0x5D, CMIDI2_CC_EFFECT_3 = 0x5D, CMIDI2_CC_CELESTE = 0x5E, CMIDI2_CC_EFFECT_4 = 0x5E, CMIDI2_CC_PHASER = 0x5F, CMIDI2_CC_EFFECT_5 = 0x5F, CMIDI2_CC_DTE_INCREMENT = 0x60, CMIDI2_CC_DTE_DECREMENT = 0x61, CMIDI2_CC_NRPN_LSB = 0x62, CMIDI2_CC_NRPN_MSB = 0x63, CMIDI2_CC_RPN_LSB = 0x64, CMIDI2_CC_RPN_MSB = 0x65, // CHANNEL MODE MESSAGES CMIDI2_CC_ALL_SOUND_OFF = 0x78, CMIDI2_CC_RESET_ALL_CONTROLLERS = 0x79, CMIDI2_CC_LOCAL_CONTROL = 0x7A, CMIDI2_CC_ALL_NOTES_OFF = 0x7B, CMIDI2_CC_OMNI_MODE_OFF = 0x7C, CMIDI2_CC_OMNI_MODE_ON = 0x7D, CMIDI2_CC_POLY_MODE_ON_OFF = 0x7E, CMIDI2_CC_POLY_MODE_ON = 0x7F, } */;
    ;
    /* Unsupported node: enum cmidi2_rpn { CMIDI2_RPN_PITCH_BEND_SENSITIVITY = 0, CMIDI2_RPN_FINE_TUNING = 1, CMIDI2_RPN_COARSE_TUNING = 2, CMIDI2_RPN_TUNING_PROGRAM = 3, CMIDI2_RPN_TUNING_BANK_SELECT = 4, CMIDI2_RPN_MODULATION_DEPTH = 5, } */;
    ;
    /* Unsupported node: enum cmidi2_meta_event_type { CMIDI2_META_SEQUENCE_NUMBER = 0X00, CMIDI2_META_TEXT = 0X01, CMIDI2_META_COPYRIGHT = 0X02, CMIDI2_META_TRACK_NAME = 0X03, CMIDI2_META_INSTRUMENT_NAME = 0X04, CMIDI2_META_LYRIC = 0X05, CMIDI2_META_MARKER = 0X06, CMIDI2_META_CUE = 0X07, CMIDI2_META_CHANNEL_PREFIX = 0X20, CMIDI2_META_END_OF_TRACK = 0X2F, CMIDI2_META_TEMPO = 0X51, CMIDI2_META_SMPTE_OFFSET = 0X54, CMIDI2_META_TIME_SIGNATURE = 0X58, CMIDI2_META_KEY_SIGNATURE = 0X59, CMIDI2_META_SEQUENCER_SPECIFIC = 0X7F, } */;
    ;
    /* Unsupported node: enum cmidi2_per_note_management_flags { CMIDI2_PER_NOTE_MANAGEMENT_RESET = 1, CMIDI2_PER_NOTE_MANAGEMENT_DETACH = 2, } */;
    ;
    /* Unsupported node: enum cmidi2_note_attribute_type { CMIDI2_ATTRIBUTE_TYPE_NONE = 0, CMIDI2_ATTRIBUTE_TYPE_MANUFACTURER = 1, CMIDI2_ATTRIBUTE_TYPE_PROFILE = 2, CMIDI2_ATTRIBUTE_TYPE_PITCH7_9 = 3, } */;
    ;
    /* Unsupported node: enum cmidi2_program_change_option_flags { CMIDI2_PROGRAM_CHANGE_OPTION_NONE = 0, CMIDI2_PROGRAM_CHANGE_OPTION_BANK_VALID = 1, } */;
    ;
    /* Unsupported node: enum cmidi2_sysex_status { CMIDI2_SYSEX_IN_ONE_UMP = 0, CMIDI2_SYSEX_START = 0x10, CMIDI2_SYSEX_CONTINUE = 0x20, CMIDI2_SYSEX_END = 0x30, } */;
    ;
    /* Unsupported node: enum cmidi2_mixed_data_set_status { CMIDI2_MIXED_DATA_STATUS_HEADER = 0x80, CMIDI2_MIXED_DATA_STATUS_PAYLOAD = 0x90, } */;
    ;
    /* Unsupported node: enum cmidi2_system_message_status { CMIDI2_SYSTEM_STATUS_MIDI_TIME_CODE = 0xF1, CMIDI2_SYSTEM_STATUS_SONG_POSITION = 0xF2, CMIDI2_SYSTEM_STATUS_SONG_SELECT = 0xF3, CMIDI2_SYSTEM_STATUS_TUNE_REQUEST = 0xF6, CMIDI2_SYSTEM_STATUS_TIMING_CLOCK = 0xF8, CMIDI2_SYSTEM_STATUS_START = 0xFA, CMIDI2_SYSTEM_STATUS_CONTINUE = 0xFB, CMIDI2_SYSTEM_STATUS_STOP = 0xFC, CMIDI2_SYSTEM_STATUS_ACTIVE_SENSING = 0xFE, CMIDI2_SYSTEM_STATUS_RESET = 0xFF, } */;
    ;
    /* Unsupported node: enum cmidi2_jr_timestamp_status { CMIDI2_JR_CLOCK = 0x10, CMIDI2_JR_TIMESTAMP = 0x20, } */;
    ;
    /* Unsupported node: enum MIDI2_SUB_ID_1 { MIDI_CI = 0xD } */;
    /* Unsupported node: enum MIDI2_SUB_ID_2 { DISCOVERY_INQUIRY = 0x70, DISCOVERY_REPLY = 0x71, INVALIDATE_MUID = 0x7E, NAK = 0x7F, PROTOCOL_NEGOTIATION_INQUIRY = 0x10, PROTOCOL_NEGOTIATION_REPLY = 0x11, SET_NEW_PROTOCOL = 0x12, TEST_NEW_PROTOCOL_I2R = 0x13, TEST_NEW_PROTOCOL_R2I = 0x14, CONFIRM_NEW_PROTOCOL_ESTABLISHED = 0x15, PROFILE_INQUIRY = 0x20, PROFILE_INQUIRY_REPLY = 0x21, SET_PROFILE_ON = 0x22, SET_PROFILE_OFF = 0x23, PROFILE_ENABLED_REPORT = 0x24, PROFILE_DISABLED_REPORT = 0x25, PROFILE_SPECIFIC_DATA = 0x2F, PROPERTY_CAPABILITIES_INQUIRY = 0x30, PROPERTY_CAPABILITIES_REPLY = 0x31, PROPERTY_HAS_DATA_INQUIRY = 0x32, PROPERTY_HAS_DATA_REPLY = 0x33, PROPERTY_GET_DATA_INQUIRY = 0x34, PROPERTY_GET_DATA_REPLY = 0x35, PROPERTY_SET_DATA_INQUIRY = 0x36, PROPERTY_SET_DATA_REPLY = 0x37, PROPERTY_SUBSCRIBE = 0x38, PROPERTY_SUBSCRIBE_REPLY = 0x39, PROPERTY_NOTIFY = 0x3F, } */;
    /* Unsupported node: enum MIDI2_CI_CAPABILITIES { PROTOCOL_NEGOTIATION_SUPPORTED = 2, PROFILE_CONFIGURATION_SUPPORTED = 4, PROPERTY_EXCHANGE_SUPPORTED = 8 } */;
    5.6;
    Reply;
    to;
    Discovery;
    Message;
    5.7;
    Invalidate;
    MUID;
    Message;
    5.8;
    NAK;
    js_var_from(JS_VAR_NAN) - js_var_from(JS_VAR_NAN);
    Message;

    return 0;
}
